sudo: required

language: c

services:
  - docker

before_install:
  - docker pull tg9541/docker-sdcc:V1.0.1

install:
  - docker run -v `pwd`:/home tg9541/docker-sdcc:V1.0.1 /bin/sh -c "sdcc --version ; sstm8 -version"

script: docker run -v `pwd`:/home tg9541/docker-sdcc:V1.0.1 /bin/sh -c "cd /home && make BOARD=test forth && make clean && make all"

deploy:
  provider: releases
  api_key:
    secure: uKmcc+O/sEYVRFPdFJzlgZEwXugAGYZOIsBksvc/HLLYrSmMmA9oIKCcXJFwkxPhHcc3jrzU2y1cZRI33Eftajj8wiTLW5kPt6A3hcDDxkIBgqgImx6u5eIWrRSk4mFcdMW00NvA4WbyTeuM/PFWP8eWP2IlUT8uM+AUJbaIP525K1RwhnjGTpE3vIIjF1s3fMPSztJcCd56inGnEXfh4ZwVLny1dfJZDVo/RSYbbVsukmqMMVGV9L+/mbv92NUX5c8owDGvwOvyTfJ+6YSiMUH1NkyT9LqbDHnnmdvVxpAiG9nwAW0Pl34QbccAmY1lshhnIq/m4IY+xm8KdhG86Nc1NrXzMS2CzjE+0kVTGMiF5eEZX5qvf0AjavGcWYJWk3mwkky4wtxuVX0CGz5Hf749UWQZj7II4XjMM/bWLuia77JuGWJNM41T5q08eMKJ62oXv94F2ma2Bv0W95kdel9d4OFchTI+wwMS3Njpc9aUrNHZcxaO6BSbFivJzODbEoaxpu/ZtGrRT5EIoQnDy/nZhSurDtpdRv5c9xTACqlaI3TCA8qfZeUbanSTAnkTzyFvkqpAcmLNkcJHcUEAWBe6Nusnrenjp1y4e/4xWBfhR3fSeoKiv/iwOszzdTagUv3dae2xAFOs2K/sXcf2FamGPamqAkaCBeaK4uojbWY=
  file:
    - "out/stm8ef-bin.zip"
    - "out/stm8ef-bin.tgz"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: TG9541/stm8ef
