name: build-test
on: [push]
jobs:
  Build-Test-Release:
    runs-on: ubuntu-latest
    container: ghcr.io/tg9541/docker-sdcc:3.9.0
    steps:
      - run: |
          echo "triggered by: ${{ github.event_name }}"
          echo "repository:   ${{ github.repository }}"
          echo "branch name:  ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          echo "; ##########################################" >> forth.asm
          echo "; # Release info added by GitHub action:"     >> forth.asm
          echo "; #   repository:   ${{ github.repository }}" >> forth.asm
          echo "; #   branch name:  ${{ github.ref }}"        >> forth.asm
          echo "; #   sha:   ${{ github.sha }}"               >> forth.asm
          echo "; ##########################################" >> forth.asm
          make BOARD=test forth
          make clean
          make all
          echo "Job status: ${{ job.status }}."
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/stm8ef-bin.zip
            out/stm8ef-bin.tgz
            out/stm8ef-rst.tgz
      - name: Keep non-release binaries
        uses: softprops/action-gh-release@v0.1.14
        if: (! startsWith(github.ref, 'refs/tags/'))
        with:
          tag_name: volatile
          files: |
            out/stm8ef-bin.zip
            out/stm8ef-bin.tgz
            out/stm8ef-rst.tgz

